version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root

  php56:
    build: ./php56
    ports:
      - "80:80"
    volumes:
      - ./src:/amp-docker/src
    working_dir: /amp-docker/src
    links:
      - db:db
      
  php71:
    build: ./php71
    ports:
      - "80:80"
    volumes:
      - ./src:/amp-docker/src
    working_dir: /amp-docker/src
    links:
      - db:db

volumes:
  db_data:
